# SENTRIX CAMERA NODES CONFIGURATION
# Format: id | location | camera_index | username | password
# Lines starting with # are ignored.

logitech | Main Entry | 0 | admin | admin123
withoutcoverlogi | Side Hallway | 2 | admin | admin123
# dell | Side Hallway | 4 | admin | admin123
